spring:
  http:
    encoding:
      enable:
        true
  datasource:
    url: jdbc:postgresql://localhost:5432/mydb
    username: postgres
    password: root

  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect


logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
    force: true
